repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=120"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest (unit)
        # Install centralized dev dependencies inside the hook venv, then run pytest with repo on PYTHONPATH
        entry: bash -c 'python -m pip install -r requirements-dev.txt && PYTHONPATH="$(pwd)" pytest -q tests/unit'
        language: python
        # dependencies are installed from requirements-dev.txt inside the hook venv
        always_run: true
        types: [python]
        pass_filenames: false
        stages: [commit]
