name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python-checks:
    name: Python Lint & Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project test deps
        run: |
          python -m pip install --upgrade pip
          # Lightweight deps for linting & basic runs; project services run in containers locally
          pip install ruff==0.6.9 pytest==8.3.3
          # Gateway & reranker optional runtime deps (non-fatal if missing in CI)
          pip install fastapi uvicorn requests jsonschema transformers sentence-transformers torch --only-binary=:all: || true

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check .

      - name: Smoke tests (scripts)
        run: |
          python --version
          # Ensure test scripts import and show help without running services
          python - <<'PY'
          import importlib.util, sys
          for f in ['test_models.py','test_gateway.py']:
              spec = importlib.util.spec_from_file_location('tmp_mod', f)
              mod = importlib.util.module_from_spec(spec)
              try:
                  spec.loader.exec_module(mod)
                  print(f"Loaded {f} OK")
              except Exception as e:
                  print(f"WARNING: {f} import failed: {e}")
          print('Smoke OK')
          PY

  docker-build:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: python-checks
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Gateway image
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: false
          load: false

      - name: Build LiteLLM container
        uses: docker/build-push-action@v6
        with:
          context: ./containers/litellm
          file: ./containers/litellm/Dockerfile
          push: false
          load: false

      - name: Docker Compose config validation
        run: |
          docker compose version
          docker compose config >/dev/null
