name: security-pr-checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dev dependencies
        run: python -m pip install -r requirements-dev.txt

      - name: Run pip-audit (report only)
        run: |
          python -m pip install pip-audit
          pip-audit --format=json --output=pip_audit.json || true

      - name: Upload pip-audit report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: pip_audit.json

      - name: Run bandit (report only)
        run: |
          python -m pip install bandit
          bandit -r services -f json -o bandit.json || true

      - name: Upload bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit.json
