name: security-nightly
on:
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC (adjust as needed)
  workflow_dispatch:

jobs:
  deep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install semgrep
        run: python -m pip install semgrep

      - name: Run semgrep (rules)
        run: |
          semgrep --config=p/ci --output=semgrep.sarif --sarif || true

      - name: Build gateway image and scan with trivy
        run: |
          docker build -t free-rag-gateway:ci -f containers/gateway/Dockerfile .
          python -m pip install trivy
          trivy image --format json -o trivy.json free-rag-gateway:ci || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep.sarif
            trivy.json
